---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl .Values.celestiaNode.home.volume.name . }}
  namespace: {{ tpl .Values.global.namespace . }}
  labels:
    {{- toYaml .Values.global.labels | trim | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.celestiaNode.home.volume.accessMode }}
  storageClassName: {{ .Values.celestiaNode.home.volume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.celestiaNode.home.volume.storage }}